apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  database: "demo_db"
  host: "mysql-service"
  port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: "root"
  username: "root"
  password: "root"

